name: 'Setup Shell Environment'
description: 'Sets up shell testing environment with shellcheck and makes scripts executable'
inputs:
  install-shellcheck:
    description: 'Whether to install shellcheck'
    required: false
    default: 'true'
  make-executable:
    description: 'Whether to make bin/ scripts executable'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Cache shellcheck
      if: inputs.install-shellcheck == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.local/bin/shellcheck
        key: ${{ runner.os }}-shellcheck-${{ runner.arch }}
        restore-keys: |
          ${{ runner.os }}-shellcheck-

    - name: Install shellcheck
      if: inputs.install-shellcheck == 'true'
      shell: bash
      run: |
        if ! command -v shellcheck >/dev/null 2>&1; then
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            sudo apt-get update -qq
            sudo apt-get install -y shellcheck
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            brew install shellcheck
          fi
        else
          echo "shellcheck already installed: $(shellcheck --version | head -1)"
        fi

    - name: Make scripts executable
      if: inputs.make-executable == 'true'
      shell: bash
      run: |
        # Make all shell scripts executable
        find . -type f -name '*.sh' -not -path './.git/*' -exec chmod +x {} \;
        echo "✓ Made shell scripts executable"
