name: Shellcheck and Bash Lint

# This workflow is kept for backwards compatibility
# Main CI is now in ci.yml
on:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          # Enable recursive globbing and run shellcheck on tracked script locations
          shopt -s globstar
          shellcheck -x bin/**/*.sh bin/*.sh scripts/**/*.sh scripts/*.sh

  bash-syntax:
    name: Bash syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bash -n (syntax check)
        run: |
          # Syntax-check all shell scripts to catch parse errors
          find . -type f -name '*.sh' -not -path './.git/*' -print0 | xargs -0 -n1 bash -n
