name: Shellcheck and Bash Lint

on:
  push:
    paths:
      - '**.sh'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/**'

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          shellcheck bin/*.sh scripts/*.sh || true

  bash-syntax:
    name: Bash syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bash -n (syntax check)
        run: |
          bash -n bin/homelab_benchmark.sh
          bash -n bin/local_benchmark.sh
