name: Smoke tests (dry-run)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - '**.sh'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/**'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make bin scripts executable
        run: |
          chmod +x bin/homelab_benchmark.sh bin/local_benchmark.sh || true

      - name: Run homelab_benchmark.sh dry-run
        run: |
          TERM=dumb bin/homelab_benchmark.sh --dry-run </dev/null || exit 1

      - name: Run local_benchmark.sh dry-run
        run: |
          TERM=dumb bin/local_benchmark.sh --dry-run </dev/null || exit 1
