name: Security Audits

on:
  push:
    branches: [ "master", "main", "release/**" ]
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

# Permissions needed to commit audit updates
permissions:
  contents: write

jobs:
  update-audits:
    name: Update Security Audits
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup shell environment
        uses: ./.github/actions/setup-shell-environment
        with:
          install-shellcheck: 'true'
          make-executable: 'true'

      - name: Run audit updater
        run: |
          echo "::group::Generating Security Audits"
          scripts/update_audits.sh
          echo "::endgroup::"

      - name: Display audit summary
        run: |
          echo "::group::Security Audit Summary"
          if [[ -f SECURITY_AUDIT.md ]]; then
            echo "=== SECURITY_AUDIT.md ===" 
            head -n 40 SECURITY_AUDIT.md
          fi
          if [[ -f SECURITY_AUDIT_LOCAL.md ]]; then
            echo "=== SECURITY_AUDIT_LOCAL.md ===" 
            head -n 40 SECURITY_AUDIT_LOCAL.md
          fi
          echo "::endgroup::"

      - name: Commit and push audit updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add audit files
          git add SECURITY_AUDIT*.md || true
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "✓ No audit changes to commit"
          else
            echo "Committing audit updates..."
            git commit -m "chore(audit): update security audit files [skip ci]"
            
            # Push back to the branch
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" "HEAD:${{ github.ref_name }}"
            echo "✓ Audit updates pushed successfully"
          fi
